-- In the domain of retail analytics, understanding customer behavior is crucial for driving business growth and enhancing customer satisfaction. One essential aspect is identifying customers who have purchased all available products, as they exhibit strong engagement with the product offerings and represent potential loyal customers.
-- Write an SQL to identify customers who have bought all the products available in products table along with total revenue generated by them. Sort the output by total revenue in decreasing order.
/*
Table:customers
+---------------+-------------+
| COLUMN_NAME   | DATA_TYPE   |
+---------------+-------------+
| customer_id   | int         |
| customer_name | varchar(15) |
+---------------+-------------+

Table:products
+--------------+-------------+
| COLUMN_NAME  | DATA_TYPE   |
+--------------+-------------+
| product_id   | int         |
| product_name | varchar(10) |
| unit_price   | int         |
+--------------+-------------+

Table:orders
+-------------+-----------+
| COLUMN_NAME | DATA_TYPE |
+-------------+-----------+
| order_id    | int       |
| customer_id | int       |
| product_id  | int       |
| quantity    | int       |
| order_date  | date      |
+-------------+-----------+
*/

select c.customer_name, sum(o.quantity*p.unit_price) as total_revenue 
from orders o
join products p on p.product_id = o.product_id
join customers c on c.customer_id = o.customer_id
group by c.customer_name
having count(distinct o.product_id) = (select count(distinct product_id) from products)
order by total_revenue desc;

